//
//  DailyChallenge.swift
//  ProjectApexCore
//
//  The official daily challenge, per Phase 0 Addendum §H.
//  In production this document is generated by the backend publishing
//  job (which runs ChallengeGenerator + the exhaustive solver) and
//  fetched by the client. The same generator also powers Test Session
//  and validation tooling.
//

public nonisolated struct DailyChallenge: Codable, Hashable, Sendable, Identifiable {
    public let id: String
    /// UTC date, e.g. "2026-07-11".
    public let dateKey: String
    public let seed: UInt64
    public let circuit: Circuit
    public let weather: Weather
    public let budget: Int
    public let simulationVersion: String
    /// Exact minimum achievable average lap, computed by the exhaustive
    /// solver. 0 = not yet computed (pre-finalization).
    public let minPossibleAverageLapMillis: Int

    /// The day's technical regulation: one option the stewards have
    /// disallowed. nil = no regulation (legacy documents, Test Lab).
    ///
    /// Why this exists. Exhaustive analysis found that a single static
    /// setup, submitted unchanged every day, beat 88% of the field on
    /// average — the daily decision wasn't deciding anything. A rotating
    /// ban is the cheapest structural fix: it makes yesterday's answer
    /// literally illegal roughly a third of the time, and it costs the
    /// player nothing in agency (two options remain in the affected
    /// category, seven categories are untouched). Measured over 180
    /// days it takes the static exploit from 88.2% to 63.6% and is the
    /// single largest contributor of the pass-6 changes.
    ///
    /// Optional so documents published before sim-1.1.0 still decode.
    public let bannedOption: EngineeringOptionID?

    public init(
        id: String,
        dateKey: String,
        seed: UInt64,
        circuit: Circuit,
        weather: Weather,
        budget: Int,
        simulationVersion: String,
        minPossibleAverageLapMillis: Int = 0,
        bannedOption: EngineeringOptionID? = nil
    ) {
        self.id = id
        self.dateKey = dateKey
        self.seed = seed
        self.circuit = circuit
        self.weather = weather
        self.budget = budget
        self.simulationVersion = simulationVersion
        self.minPossibleAverageLapMillis = minPossibleAverageLapMillis
        self.bannedOption = bannedOption
    }

    /// Player-facing regulation text for the brief screen.
    /// nil when the day has no regulation.
    public var regulationText: String? {
        guard let bannedOption else { return nil }
        let option = OptionLibrary.option(bannedOption)
        return "\(option.category.displayName): \(option.displayName) is not permitted at this event."
    }

    /// True when the regulation still leaves a legal setup inside the
    /// budget. The publishing job must assert this before publishing —
    /// banning the cheapest option in a category raises the floor.
    public var isSatisfiable: Bool {
        OptionLibrary.minimumTotalCost(banned: bannedOption) <= budget
    }

    /// Copy with the solver-computed minimum filled in (backend
    /// publishing flow: generate → solve → finalize → publish).
    public func finalized(minPossibleAverageLapMillis: Int) -> DailyChallenge {
        DailyChallenge(
            id: id, dateKey: dateKey, seed: seed, circuit: circuit,
            weather: weather, budget: budget, simulationVersion: simulationVersion,
            minPossibleAverageLapMillis: minPossibleAverageLapMillis,
            bannedOption: bannedOption
        )
    }
}
